plugins {
    id 'com.android.application'
}

android {
    namespace 'com.github.ykocaman59bit.tirnav'
    compileSdk 33

    defaultConfig {
        applicationId "com.github.ykocaman59bit.tirnav"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.webkit:webkit:1.7.0'
}
