name: TIRNAV Android APK Builder

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Kodlarını İndir
        uses: actions/checkout@v4

      - name: Java (JDK) Ortamını Kur
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle Kurulumu
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '7.5'

      - name: Launcher ikonunu hazırla
        run: |
          mkdir -p app/src/main/res/mipmap-hdpi
          sudo apt-get update
          sudo apt-get install -y librsvg2-bin

          rsvg-convert \
            -w 192 \
            -h 192 \
            icon.svg \
            -o app/src/main/res/mipmap-hdpi/ic_launcher.png

          cp \
            app/src/main/res/mipmap-hdpi/ic_launcher.png \
            app/src/main/res/mipmap-hdpi/ic_launcher_round.png

      - name: TIRNAV APK Derle
        run: |
          gradle assembleDebug --no-daemon

          cp \
            app/build/outputs/apk/debug/app-debug.apk \
            app/build/outputs/apk/debug/TIRNAV.apk

      - name: APK Dosyasını Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: TIRNAV
          path: app/build/outputs/apk/debug/TIRNAV.apk
          if-no-files-found: error
          retention-days: 1
